services:
  werewolf-agent:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true          # Enable TTY
    stdin_open: true   # Keep stdin open
    environment:
      - TERM=xterm-256color
    models:
      chat:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL
      tools:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_TOOLS_MODEL

models:
  chat:
    model: ai/qwen2.5:1.5B-F16
  tools:
    model: hf.co/menlo/lucy-128k-gguf:q4_k_m
